# Generated by Django 4.1.6 on 2023-02-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='account_holder')),
                ('social_media', models.URLField()),
                ('profit', models.CharField(max_length=100)),
                ('bank_acc', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('followers', models.PositiveBigIntegerField()),
                ('about', models.TextField()),
            ],
        ),
    ]
