# Generated by Django 4.1.6 on 2023-02-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHUL_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand_type', models.CharField(max_length=100)),
                ('company_about', models.TextField()),
                ('company_total_ads', models.IntegerField(default=0)),
            ],
        ),
    ]
