# Generated by Django 4.1.6 on 2023-02-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RHUL_API', '0002_companyinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_about',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_total_ads',
            new_name='total_ads',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='brand_type',
            new_name='type',
        ),
    ]
